# Generated by Django 5.1.1 on 2024-09-27 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestapp', '0003_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_and_white_price', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
                ('color_price', models.DecimalField(decimal_places=2, default=0.25, max_digits=5)),
                ('fast_print_surcharge', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('delivery_surcharge', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.05, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='nestuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nestapp.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='orders/')),
                ('page_count', models.IntegerField()),
                ('color_option', models.CharField(choices=[('bw', 'Black & White'), ('color', 'Colored')], max_length=50)),
                ('file_type', models.CharField(blank=True, default='none', max_length=50)),
                ('fast_option', models.BooleanField(default=False)),
                ('delivery_option', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed')], default='processing', max_length=50)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nestapp.pickuplocation')),
            ],
        ),
    ]
