# Generated by Django 5.1.1 on 2024-10-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestapp', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.URLField(),
        ),
    ]
